# Netlify 部署配置文件
[build]
  # 发布目录（项目根目录）
  publish = "."
  
  # 构建命令（静态文件无需构建）
  command = "echo 'AI仁波切部署完成！'"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 重定向规则
[[redirects]]
  # SPA 路由支持
  from = "/*"
  to = "/index.html"
  status = 200

# 头部配置（安全和性能优化）
[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 缓存控制
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API 代理配置（解决 CORS 问题）
[[redirects]]
  from = "/api/*"
  to = "https://api.dify.ai/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# 错误页面
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404